; note: most of the accent colors are set to the green of that color scheme, feel free to change it to your preferred color

[Purple]
button = B693CE
button-active = B693CE

[Summer_Sky]
button = e2a16c
button-active = e2a16c

[NyanCat]
button = EDA1DB
button-active = EDA1DB

[Stray]
button = e1b72d
button-active = e1b72d

[MyMelody]
button = f7c1ef
button-active = f7c1ef
